version: '3'
services:
  discord-event-bot:
    build: '.'
    ports:
      - "3000:3000"
    command: yarn start:dev
    volumes:
      - ./dist:/usr/app/dist
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo/discord-event-bot
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data/db:/data/db

